// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRExZ1pYKhjIfcXEfzCVA2KSz2HhjbtpA',
    appId: '1:557329062230:web:00f9d5b1a0e94705649ef7',
    messagingSenderId: '557329062230',
    projectId: 'mangement-system-219c0',
    authDomain: 'mangement-system-219c0.firebaseapp.com',
    storageBucket: 'mangement-system-219c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_2HDp4qBqGDHOvk1IcfkzniG8B9FBGw',
    appId: '1:557329062230:android:c7882a7985177f80649ef7',
    messagingSenderId: '557329062230',
    projectId: 'mangement-system-219c0',
    storageBucket: 'mangement-system-219c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSOvmjPeih0ZCCO31dXQf57ub33zZYek',
    appId: '1:557329062230:ios:cf67877b2c8f2a02649ef7',
    messagingSenderId: '557329062230',
    projectId: 'mangement-system-219c0',
    storageBucket: 'mangement-system-219c0.appspot.com',
    iosClientId: '557329062230-om2711c1eob03h96r2430ftelpdl89fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSOvmjPeih0ZCCO31dXQf57ub33zZYek',
    appId: '1:557329062230:ios:cf67877b2c8f2a02649ef7',
    messagingSenderId: '557329062230',
    projectId: 'mangement-system-219c0',
    storageBucket: 'mangement-system-219c0.appspot.com',
    iosClientId: '557329062230-om2711c1eob03h96r2430ftelpdl89fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.management',
  );
}
